### ISSUE TITLE
x86-video-intel-git - error: pathspec 'modesetting' did not match any file(s) known to git

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/moonbase-xorg#500]
Downloading GIT module for module xf86-video-intel-git
Cloning into 'xf86-video-intel-git-beta'...
remote: Counting objects: 55687, done.
remote: Compressing objects: 100% (11441/11441), done.
remote: Total 55687 (delta 44464), reused 55335 (delta 44198)
Receiving objects: 100% (55687/55687), 9.76 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (44464/44464), done.
Init and update the submodules
Creating xf86-video-intel-git-beta.tar.bz2
Building xf86-video-intel-git version beta
error: pathspec 'modesetting' did not match any file(s) known to git.
Creating /var/log/lunar/compile/xf86-video-intel-git-beta.xz 
! Problem detected during BUILD
root@tulp ~ #

cheers, Marco

**Comment by v4hn** [comment]
It complains that they don't have a `modesetting` branch around anymore.
So what's the branch we *should* use now?

**Comment by Florin65** [comment]
see the arch choice https://www.archlinux.org/packages/testing/x86_64/xf86-video-intel/

**Comment by mwgrient** [comment]
I found out that if the modesetting option was disabled in the BUILD file (xf86-video-intel-git) and some other 'things', so the package builds with this:

(

#  git checkout modesetting &&
#  touch NEWS AUTHORS INSTALL &&
#  echo "SUBDIRS = src" > Makefile.am &&
  . /etc/profile.d/x11r7.rc &&
  default_cvs_build

) > $C_FIFO 2>&1

regards, Marco

**Comment by mwgrient** [comment]
the BOLD text was initially commented text, with a # sign, But I see that these are gone. :-(

**Comment by v4hn** [comment]
heya,
sounds reasonable to me.
@mwgrient do you mind creating a pull-request that makes the module work again?

**Comment by mwgrient** [comment]
Hey, ok, I'll look into it. Which means that I have to install Lunar-Linux first... and  I am bussy with that.
Talk to you later!
Regrads, Marco.

**Comment by mwgrient** [comment]
ok, this is my first pull request. :-). Can it be done by using this website, or do I have to do it with git/commandline? Or whats the preferrd way?

**Comment by v4hn** [comment]
:D How did you discover the issue if you didn't have lunar installed?

Fork the github repository, look for any howto for git to push your change to a branch on your github fork (I suppose there are lots of them around...) and then you request a pull-request from this website.
Good luck :-)

**Comment by mwgrient** [comment]
I did had lunar installed, but spoiled my system and decided to build it fresh up again. That takes about 5 hours to have my system up-and-running.

Thanks for the info.

**Comment by mwgrient** [comment]
I have one problem with my "fix": first time run is building fine, seccond en further ones do not build! -->

  CC       sna_blt.lo
  CC       sna_composite.lo
  CC       sna_cpu.lo
  CC       sna_damage.lo
  CC       sna_display.lo
  CC       sna_display_fake.lo
make[4]: *** No rule to make target '../../.git/refs/heads/master', needed by 'git_version.h'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/usr/src/xf86-video-intel-git-beta/src/sna'
make[3]: *** [Makefile:670: all-recursive] Error 1
make[3]: Leaving directory '/usr/src/xf86-video-intel-git-beta/src/sna'
make[2]: *** [Makefile:613: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/xf86-video-intel-git-beta/src'
make[1]: *** [Makefile:486: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/xf86-video-intel-git-beta'
make: *** [Makefile:418: all] Error 2
Creating /var/log/lunar/compile/xf86-video-intel-git-beta.xz 
! Problem detected during BUILD
root@tulp ~ #   CC       sna_blt.lo
  CC       sna_composite.lo
  CC       sna_cpu.lo
  CC       sna_damage.lo
  CC       sna_display.lo
  CC       sna_display_fake.lo
make[4]: *** No rule to make target '../../.git/refs/heads/master', needed by 'git_version.h'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/usr/src/xf86-video-intel-git-beta/src/sna'
make[3]: *** [Makefile:670: all-recursive] Error 1
make[3]: Leaving directory '/usr/src/xf86-video-intel-git-beta/src/sna'
make[2]: *** [Makefile:613: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/xf86-video-intel-git-beta/src'
make[1]: *** [Makefile:486: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/xf86-video-intel-git-beta'
make: *** [Makefile:418: all] Error 2
Creating /var/log/lunar/compile/xf86-video-intel-git-beta.xz 
! Problem detected during BUILD
root@tulp ~ # 

Does someone knows this git-error?

**Comment by v4hn** [comment]
what do you mean by "first time"?
If I comment the three lines you indicated, `lin xf86-video-intel-git` succeeds for me - also if I run it again and again...

**Comment by mwgrient** [comment]
First time: I mean that the package must be downloaded first, and then the build process can start (sorry, translation problems :) ). But if it is working for you, then fine. Thanks for the response!

**Comment by mwgrient** [comment]
I have forked it, added the changes en did a pull request.

**Comment by v4hn** [comment]
Sorry for taking so long. I'm too busy. :(
You successfully forked it and added commits in your fork(I can see them [here](https://github.com/mwgrient/moonbase-xorg/commits/master)), but you didn't create a pull-request that asks to merge the branch "master" in your fork into the "master" branch of the upstream repository!
If you do, this will be automatically tested and it allows the maintainers to merge your change upstream with two clicks in the browser.

**Comment by mwgrient** [comment]
I have done my best :-) How about now?

**Comment by v4hn** [comment]
I just merged your pull-request #501.
Congratulations on your first merged pull-request :+1:
