### ISSUE TITLE
Please update all DETAILS with http: //*.freedesktop.org to https: //*.freedesktop.org

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-xorg#542]
All packages from freedesktop.org can not be downloaded. The http link in DETAILS needs to be changed to https to update normally.
Under normal circumstances, I use the command:
` find / -name "DETAILS" -type f | xargs sed-i '/ freedesktop / s / http / https / g' `
local DETAILS file changes in order to properly update freedesktop.org Package, such as xcb-util-image.

Please update all DETAILS with http: //*.freedesktop.org to https: //*.freedesktop.org

`MODULE=xcb-util-image
         VERSION=0.4.0
          SOURCE=$MODULE-$VERSION.tar.bz2
      SOURCE_URL=http://xcb.freedesktop.org/dist
      SOURCE_VFY=sha256:2db96a37d78831d643538dd1b595d7d712e04bdccf8896a5e18ce0f398ea2ffc
   MODULE_PREFIX=${X11R7_PREFIX:-/usr}
        WEB_SITE=http://xcb.freedesktop.org/
         ENTERED=20110608
         UPDATED=20150405
           SHORT="Image extensions for libxcb"

cat << EOF
These experimental libraries provide convenience functions and
interfaces which make the raw X protocol more usable
EOF`

MUST BE

`MODULE=xcb-util-image
         VERSION=0.4.0
          SOURCE=$MODULE-$VERSION.tar.bz2
      SOURCE_URL=**https**://xcb.freedesktop.org/dist
      SOURCE_VFY=sha256:2db96a37d78831d643538dd1b595d7d712e04bdccf8896a5e18ce0f398ea2ffc
   MODULE_PREFIX=${X11R7_PREFIX:-/usr}
        WEB_SITE=**https**://xcb.freedesktop.org/
         ENTERED=20110608
         UPDATED=20150405
           SHORT="Image extensions for libxcb"

cat << EOF
These experimental libraries provide convenience functions and
interfaces which make the raw X protocol more usable
EOF`

**Comment by v4hn** [comment]
> All packages from freedesktop.org can not be downloaded.
> The http link in DETAILS needs to be changed to https to update normally.

I can't reproduce this. Yes, the server yields a 301 Moved Permanently
for http requests and redirects to the corresponding https url, but wget handles
this without error. Could you please provide the output of `lin -g xcb-util-image`
when it fails for you?

**Comment by lhw828** [comment]
@v4hn 
![https](https://user-images.githubusercontent.com/1897722/32976678-3a3446fc-cc57-11e7-9595-be17a613515a.png)

**Comment by lhw828** [comment]
@v4hn 
![https2](https://user-images.githubusercontent.com/1897722/32976688-6e2814c0-cc57-11e7-97a3-60314f7eb9db.png)

**Comment by v4hn** [comment]
Sorry for the late response.

It seems to me that you did not install the `ca-certificates` package and thus can't verify their certificates either way. However, without the redirect `lget` still manages to download the package even without verification of the certificate.

So feel free to provide a pull-request that changes all the relevant URLs and we will merge it to improve user experience.
