### ISSUE TITLE
mesa-lib:build errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-xorg#699]
Building mesa-lib version 19.2.1
patching file meson.build
Hunk #1 succeeded at 1300 (offset -28 lines).
patching file src/egl/meson.build
patching file src/meson.build
Hunk #1 succeeded at 106 (offset -6 lines).
patching file include/GL/gl.h
patching file include/GL/gl_mangle.h
patching file include/GL/glx.h
patching file include/GL/glx_mangle.h
patching file include/HaikuGL/README
patching file include/meson.build
patching file src/gallium/targets/libgl-xlib/xlib.c
patching file src/mapi/glapi/gen/gl_procs.py
patching file src/mapi/glapi/gen/gl_x86-64_asm.py
patching file src/mapi/glapi/gen/gl_x86_asm.py
patching file src/mapi/glapi/glapi.h
patching file src/mapi/glapi/glapi_dispatch.c
patching file src/mapi/glapi/glapi_getproc.c
patching file src/mapi/mapi_abi.py
patching file src/mapi/mapi_glapi.c
patching file src/mesa/drivers/osmesa/osmesa.c
patching file src/mesa/drivers/x11/glxapi.c
patching file include/meson.build
patching file include/meson.build
patching file include/meson.build
patching file include/meson.build
The Meson build system
Version: 0.52.0
Source dir: /usr/src/mesa-19.2.1
Build dir: /usr/src/mesa-19.2.1/build
Build type: native build
Program python found: YES (/usr/bin/python)
Project name: mesa
Project version: 19.2.1
Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
Appending CXXFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
C compiler for the host machine: gcc (gcc 9.2.0 "gcc (GCC) 9.2.0")
C linker for the host machine: GNU ld.bfd 2.32
Appending CXXFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
C++ compiler for the host machine: g++ (gcc 9.2.0 "g++ (GCC) 9.2.0")
C++ linker for the host machine: GNU ld.bfd 2.32
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program pkg-config found: YES (/usr/bin/pkg-config)
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency vdpau found: YES 1.1.1
Run-time dependency xvmc found: YES 1.0.12
Run-time dependency xv found: YES 1.0.11
Run-time dependency libomxil-bellagio found: YES 0.9.3
Run-time dependency libva found: YES 1.5.0
Program python3 found: YES (/usr/bin/python3)

meson.build:777:2: ERROR: Problem encountered: Python (3.x) mako module >= 0.8.0 required to build mesa.

A full log can be found at /usr/src/mesa-19.2.1/build/meson-logs/meson-log.txt
Creating /var/log/lunar/compile/mesa-lib-19.2.1.xz 
! Problem detected during BUILD

but my "mako" already installed.

**Comment by florin65** [comment]
do a 'lin -rc python-mako'. it remained the install for the previous version of python.
