### ISSUE TITLE
mesa-lib:some errors about libunwind.h

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-xorg#750]
[1574/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/driver_trace_tr_dump.c.o
[1575/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/hud_font.c.o
[1576/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/hud_hud_cpu.c.o
[1577/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/hud_hud_context.c.o
[1578/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/hud_hud_diskstat.c.o
[1579/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/hud_hud_sensors_temp.c.o
[1580/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/indices_u_primconvert.c.o
[1581/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/hud_hud_fps.c.o
[1582/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/hud_hud_driver_query.c.o
[1583/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/pipebuffer_pb_bufmgr_debug.c.o
FAILED: src/gallium/auxiliary/libgallium.a.p/pipebuffer_pb_bufmgr_debug.c.o 
gcc -Isrc/gallium/auxiliary/libgallium.a.p -Isrc/gallium/auxiliary -I../src/gallium/auxiliary -Isrc/loader -I../src/loader -I../src/gallium/include -Isrc -I../src -Iinclude -I../include -I../src/gallium/auxiliary/util -Isrc/compiler/nir -I../src/compiler/nir -Isrc/util -I../src/util -I/usr/include/libdrm -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -O3 -ffunction-sections -fdata-sections '-DPACKAGE_VERSION="21.3.6"' '-DPACKAGE_BUGREPORT="https://gitlab.freedesktop.org/mesa/mesa/-/issues"' -DUSE_ELF_TLS -DHAVE_ST_VDPAU -DENABLE_ST_OMX_BELLAGIO=0 -DENABLE_ST_OMX_TIZONIA=0 -DHAVE_VA_SURFACE_ATTRIB_DRM_FORMAT_MODIFIERS -DHAVE_X11_PLATFORM -DHAVE_XCB_PLATFORM -DGLX_INDIRECT_RENDERING -DGLX_DIRECT_RENDERING -DGLX_USE_DRM -DHAVE_DRM_PLATFORM -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE___BUILTIN_TYPES_COMPATIBLE_P -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUNC_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC_ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUTE_PACKED -DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -DHAVE_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_UINT128 -DUSE_SSE41 -DUSE_GCC_ATOMIC_BUILTINS -DUSE_X86_64_ASM -DMAJOR_IN_SYSMACROS -DHAS_SCHED_H -DHAS_SCHED_GETAFFINITY -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_SYS_SHM_H -DHAVE_CET_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_TIMESPEC_GET -DHAVE_MEMFD_CREATE -DHAVE_RANDOM_R -DHAVE_FLOCK -DHAVE_STRTOK_R -DHAVE_GETRANDOM -DHAVE_QSORT_R -DHAVE_PROGRAM_INVOCATION_NAME -DHAVE_POSIX_MEMALIGN -DHAVE_DIRENT_D_TYPE -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -DHAVE_ZSTD -DHAVE_COMPRESSION -DHAVE_PTHREAD -DHAVE_PTHREAD_SETAFFINITY -DHAVE_LIBDRM -DLLVM_AVAILABLE '-DMESA_LLVM_VERSION_STRING="12.0.1"' -DLLVM_IS_SHARED=1 -DDRAW_LLVM_AVAILABLE -DUSE_LIBGLVND=1 -DMESA_EXECMEM -DHAVE_LIBUNWIND -DHAVE_WAYLAND_PLATFORM -DWL_HIDE_DEPRECATED -DHAVE_OPENMP -DHAVE_DRI3 -DHAVE_DRI3_MODIFIERS -DHAVE_GALLIUM_EXTRA_HUD=1 -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVK_USE_PLATFORM_DISPLAY_KHR -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=empty-body -Werror=incompatible-pointer-types -Werror=int-conversion -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-format-truncation -fno-math-errno -fno-trapping-math -fno-common -Werror=format -Wformat-security -O2 -march=x86-64 -pipe -D_FORTIFY_SOURCE=2 -fPIC -pthread -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Werror=pointer-arith -MD -MQ src/gallium/auxiliary/libgallium.a.p/pipebuffer_pb_bufmgr_debug.c.o -MF src/gallium/auxiliary/libgallium.a.p/pipebuffer_pb_bufmgr_debug.c.o.d -o src/gallium/auxiliary/libgallium.a.p/pipebuffer_pb_bufmgr_debug.c.o -c ../src/gallium/auxiliary/pipebuffer/pb_bufmgr_debug.c
In file included from ../src/gallium/auxiliary/pipebuffer/pb_bufmgr_debug.c:42:
../src/util/u_debug_stack.h:35:10: fatal error: libunwind.h: No such file or directory
   35 | #include <libunwind.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
[1584/2609] Compiling C object src/gallium/auxiliary/libgallium.a.p/pipebuffer_pb_bufmgr_cache.c.o
[1585/2609] Linking target src/glx/libGLX_mesa.so.0.0.0
[1586/2609] Linking target src/amd/vulkan/libvulkan_radeon.so
[1587/2609] Linking target src/intel/vulkan/libvulkan_intel.so
najia:build stop

In fact, libunwind has already been installed.

**Comment by florin65** [comment]
Please re-lin libunwind and try it again. Eventually try lin -rc mesa-lib after the libunwind rebuild.

**Comment by lhw828** [comment]
I tryed lin -rc libunwind then lin -rc mesa-lib,Still prompt the same error.

**Comment by lhw828** [comment]
https://serenity.stderr.eu/ci-lunar/job/moonbase-xorg/408/console

In CI, this problem also exists

**Comment by stumbles** [comment]
lld uses its own libunwind from the llvm git repository. Install lld.

**Comment by lhw828** [comment]
Ah, I installing lld and re-lin llvm then lin -rc mesa-lib,some errors liks this:

[1868/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/meson-generated_.._rasterizer_core_backends_gen_rasterizer0.cpp.o
[1869/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/meson-generated_.._rasterizer_core_backends_gen_rasterizer1.cpp.o
[1870/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/swr_context.cpp.o
[1871/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/meson-generated_.._rasterizer_core_backends_gen_rasterizer2.cpp.o
[1872/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/swr_state.cpp.o
[1873/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/swr_tex_sample.cpp.o
[1874/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/swr_draw.cpp.o
[1875/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/swr_scratch.cpp.o
[1876/2623] Compiling C++ object src/gallium/drivers/swr/libmesaswr.a.p/swr_shader.cpp.o
FAILED: src/gallium/drivers/swr/libmesaswr.a.p/swr_shader.cpp.o 
g++ -Isrc/gallium/drivers/swr/libmesaswr.a.p -Isrc/gallium/drivers/swr -I../src/gallium/drivers/swr -Iinclude -I../include -Isrc -I../src -Isrc/mapi -I../src/mapi -Isrc/mesa -I../src/mesa -I../src/gallium/include -Isrc/gallium/auxiliary -I../src/gallium/auxiliary -Isrc/gallium/drivers/swr/rasterizer/codegen -I../src/gallium/drivers/swr/rasterizer/codegen -Isrc/gallium/drivers/swr/rasterizer/core -I../src/gallium/drivers/swr/rasterizer/core -Isrc/gallium/drivers/swr/rasterizer/jitter -I../src/gallium/drivers/swr/rasterizer/jitter -I../src/gallium/drivers/swr/rasterizer/archrast -Isrc/gallium/drivers/swr/rasterizer -I../src/gallium/drivers/swr/rasterizer -Isrc/util -I../src/util -Isrc/gallium/drivers/swr/rasterizer/core/backends -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O3 -ffunction-sections -fdata-sections '-DPACKAGE_VERSION="21.3.6"' '-DPACKAGE_BUGREPORT="https://gitlab.freedesktop.org/mesa/mesa/-/issues"' -DUSE_ELF_TLS -DHAVE_ST_VDPAU -DENABLE_ST_OMX_BELLAGIO=1 -DENABLE_ST_OMX_TIZONIA=0 -DHAVE_VA_SURFACE_ATTRIB_DRM_FORMAT_MODIFIERS -DHAVE_X11_PLATFORM -DHAVE_XCB_PLATFORM -DGLX_INDIRECT_RENDERING -DGLX_DIRECT_RENDERING -DGLX_USE_DRM -DHAVE_DRM_PLATFORM -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE___BUILTIN_TYPES_COMPATIBLE_P -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUNC_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC_ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUTE_PACKED -DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -DHAVE_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_UINT128 -DUSE_SSE41 -DUSE_GCC_ATOMIC_BUILTINS -DUSE_X86_64_ASM -DMAJOR_IN_SYSMACROS -DHAS_SCHED_H -DHAS_SCHED_GETAFFINITY -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_SYS_SHM_H -DHAVE_CET_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_TIMESPEC_GET -DHAVE_MEMFD_CREATE -DHAVE_RANDOM_R -DHAVE_FLOCK -DHAVE_STRTOK_R -DHAVE_GETRANDOM -DHAVE_QSORT_R -DHAVE_PROGRAM_INVOCATION_NAME -DHAVE_POSIX_MEMALIGN -DHAVE_DIRENT_D_TYPE -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -DHAVE_ZSTD -DHAVE_COMPRESSION -DHAVE_PTHREAD -DHAVE_PTHREAD_SETAFFINITY -DHAVE_LIBDRM -DLLVM_AVAILABLE '-DMESA_LLVM_VERSION_STRING="13.0.1"' -DLLVM_IS_SHARED=1 -DDRAW_LLVM_AVAILABLE -DUSE_LIBGLVND=1 -DMESA_EXECMEM -DHAVE_LIBUNWIND -DHAVE_WAYLAND_PLATFORM -DWL_HIDE_DEPRECATED -DHAVE_OPENMP -DHAVE_DRI3 -DHAVE_DRI3_MODIFIERS -DHAVE_GALLIUM_EXTRA_HUD=1 -DHAVE_LIBSENSORS=1 -DVK_USE_PLATFORM_DISPLAY_KHR -Werror=return-type -Werror=empty-body -Wno-non-virtual-dtor -Wno-missing-field-initializers -Wno-format-truncation -fno-math-errno -fno-trapping-math -flifetime-dse=1 -Werror=format -Wformat-security -O2 -march=x86-64 -pipe -D_FORTIFY_SOURCE=2 -fPIC -pthread -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Werror=pointer-arith -fno-strict-aliasing -Wno-aligned-new -mavx -DHAVE_SWR_AVX2 -DHAVE_SWR_AVX -MD -MQ src/gallium/drivers/swr/libmesaswr.a.p/swr_shader.cpp.o -MF src/gallium/drivers/swr/libmesaswr.a.p/swr_shader.cpp.o.d -o src/gallium/drivers/swr/libmesaswr.a.p/swr_shader.cpp.o -c ../src/gallium/drivers/swr/swr_shader.cpp
In file included from ../src/gallium/drivers/swr/rasterizer/jitter/builder.h:168,
                 from ../src/gallium/drivers/swr/swr_shader.cpp:43:
../src/gallium/drivers/swr/rasterizer/jitter/builder_mem.h: In member function 'virtual llvm::CallInst* SwrJit::Builder::MASKED_LOAD(llvm::Value*, unsigned int, llvm::Value*, llvm::Value*, const llvm::Twine&, llvm::Type*, SwrJit::Builder::MEM_CLIENT)':
../src/gallium/drivers/swr/rasterizer/jitter/builder_mem.h:87:36: error: cannot convert 'llvm::Value*' to 'llvm::Type*'
   87 |     return IRB()->CreateMaskedLoad(Ptr, AlignType(Align), Mask, PassThru, Name);
      |                                    ^~~
      |                                    |
      |                                    llvm::Value*
In file included from ../src/gallium/drivers/swr/rasterizer/jitter/jit_pch.hpp:50,
                 from ../src/gallium/drivers/swr/rasterizer/jitter/JitManager.h:32,
                 from ../src/gallium/drivers/swr/swr_shader.cpp:32:
/usr/include/llvm/IR/IRBuilder.h:755:36: note:   initializing argument 1 of 'llvm::CallInst* llvm::IRBuilderBase::CreateMaskedLoad(llvm::Type*, llvm::Value*, llvm::Align, llvm::Value*, llvm::Value*, const llvm::Twine&)'
  755 |   CallInst *CreateMaskedLoad(Type *Ty, Value *Ptr, Align Alignment, Value *Mask,
      |                              ~~~~~~^~
[1877/2623] Linking target src/amd/vulkan/libvulkan_radeon.so
[1878/2623] Linking target src/gallium/drivers/swr/libswrAVX2.so.0.0.0
[1879/2623] Linking target src/intel/vulkan/libvulkan_intel.so
[1880/2623] Linking target src/gallium/drivers/swr/libswrAVX.so.0.0.0
[1881/2623] Linking target src/mesa/drivers/dri/libmesa_dri_drivers.so
ninja: build stopped: subcommand failed.

**Comment by stumbles** [comment]
There's a few other modules needing a relin after lld, though I forget which ones.

I think we need to use lld as depends for all modules requiring llvm as it obviously pulls in llvm and this can be avoided.

Having said that, mesa-lib (current version and your PR for 21.3.6 will still fail with;

FAILED: src/gallium/drivers/swr/libmesaswr.a.p/swr_shader.cpp.o 
FAILED: src/gallium/drivers/swr/libmesaswr.a.p/rasterizer_jitter_builder_misc.cpp.o 
FAILED: src/gallium/drivers/swr/libmesaswr.a.p/rasterizer_jitter_blend_jit.cpp.o 
FAILED: src/gallium/drivers/swr/libmesaswr.a.p/rasterizer_jitter_builder.cpp.o 
FAILED: src/gallium/drivers/swr/libmesaswr.a.p/rasterizer_jitter_builder_mem.cpp.o 

After looking into it I've not found a fix as such, though https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/13273/commits has some proposed patches to get around llvm 13 and 14. Haven't tried them.

**Comment by lhw828** [comment]
The mesa-lib can compile normally through this pr when  I install lld,
