### ISSUE TITLE
glslang:popd: directory stack empty

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-xorg#768]
Checking dependencies for glslang 
Building glslang version 11.9.0
cmake: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
/var/lib/lunar/moonbase/xorg/vulkan/glslang/BUILD: line 10: popd: directory stack empty

**Comment by stumbles** [comment]
You've fallen into the nasty icu4c versioned so name trap that always happens on a icu4c version bump. 

You WILL need to do a lunar fix. I'd suggest lunar fix libxml first and any of the lowest level dependencies you have installed and work your way up. Or, as I mentioned, lunar fix and let run to the end. If you do that you will find a whole bunch of failed modules in /usr/src at which time you can either relin them or delete them. I'd suggest relin them for good measure.

**Comment by lhw828** [comment]
lunar fix fixed this.
